name: Docker

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 60
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/docker-intel-gpu-tools:latest
        push: true
